### ISSUE TITLE
iolaSay

### ISSUE THREAD

**Issue by 0B6AE8H** [iola1999/iola1999.github.io#3]

**Comment by iola1999** [comment]
不清楚现在是否还能方便地抓取对局数据。
我做的时候数据是来自王者营地的，你可以抓包试试看（fiddler 或者 iOS 上 的 stream）。有问题欢迎交流。

**Comment by 0B6AE8H** [comment]
学长好
我的毕业设计是想做一个王者荣耀的胜率预测&nbsp; &nbsp;现在已经开始进行开题登记了&nbsp; &nbsp;但是我短时间无法抓取足够数量的对局数据&nbsp; &nbsp;后来查资料的时候看到你19年已经做过类似的工作了&nbsp; &nbsp;想问一下你当时抓取的对局信息现在还在不在&nbsp; &nbsp;能不能分享一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iola1999/iola1999.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 晚上7:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iola1999/iola1999.github.io] iolaSay (#3)





 
不清楚现在是否还能方便地抓取对局数据。
 我做的时候数据是来自王者营地的，你可以抓包试试看（fiddler 或者 iOS 上 的 stream）。有问题欢迎交流。

**Comment by iola1999** [comment]
那些数据已经过时了......没有参考意义，你非要的话，倒也还有存档，只有 7 万场对局。
建议先评估一下现在王者营地是否还能方便地抓取数据，好抓的话一两周数据就够了。爬数据过程中再去利用旧数据，研究下要用的机器学习算法啥的。

**Comment by 0B6AE8H** [comment]
现在王者营地通过抓包也能获得对局信息&nbsp; &nbsp; &nbsp;也看到了其他游戏的参考案例&nbsp; &nbsp;我想先拿到数据评估一下自己的数据处理能力
也让指导老师对我的数据量有个估计&nbsp; &nbsp;给我顺利开题
麻烦学长找一下当时的数据&nbsp; 分享一下
顺便问一下&nbsp; 学长当时想做的胜率预测&nbsp; &nbsp;考虑过采用何种算法吗

**Comment by iola1999** [comment]
找了下数据，发现有十万场对局了......不过我个人理解的话，这个数据量做胜率预测等等可能不够？

发到你的 QQ 邮箱了，附带了部分说明。

做毕设项目的话，做个交互比较舒服的前端应该会很有亮点，也很好水。

另外，在 Github 上搜索 ssl.kohsocialapp.qq.com:10001、getmatchlist 等信息，应该能找到许多参考代码。

机器学习算法啥的，俺也不会。没有怎么研究，跑去写前端了。
