### ISSUE TITLE
关于L2TP闪讯多拨

### ISSUE THREAD

**Issue by nanako7z** [iola1999/iola1999.github.io#4]
你好想请教需要L2TP拨号的闪讯要如何多拨呢，已经实现闪讯拨号，我们学校第一层不是pppoe拨号而是DHCP分配的，使用的是openwrt，添加第二个L2TP的接口不能拨号

**Comment by iola1999** [comment]
很久没折腾了，印象中大概可以这样操作，不一定有用：
虚拟 WAN 得到两个接口，先看看这两个能不能正常获取两个内网 IP；能的话加两个 l2tp 接口，分别跟前面两个接口各自设置到同一防火墙里，再看看能不能拨号成功。
另外建议有条件还是跟同学多个账号拨号，单账号并发多拨成功率太低了。
另外学校宿舍很多线路都是百兆的，即使成功了也只能提升上行。

**Comment by nanako7z** [comment]
你好，我们第一层是DHCP分配的，但是需要网页认证，我不清楚要如何分开来认证，我有多过可以认证的账号以及多个闪讯账号，你说的L2TP和DHCP对应放到一个防火墙里的方法我前面没有看到过，下次我尝试一下，线路的话我这个应该是千兆口，而且就我了解有些闪讯账号给的就是200M带宽，我目前所使用的这个账号就是，而其他账号只有百兆，所以如果能多拨的话下行应该是可以有提升的，方便加个QQ联系吗，想请教更多问题

**Comment by nanako7z** [comment]
我尝试虚拟一个WAN出来可以成功拿到两个内网的ip，但是不知道如何各自通过内网的网页认证

**Comment by iola1999** [comment]
这个认证状态应该是可以保持的？可以的话很简单了，接口分别设置不同的 MAC 地址，每次只连接上一个接口做认证。最终期望连接恢复时都是已认证的。
如果每次连接都要认证，那要通过路由规则指定请求应该走哪个出口，这块我不熟。

加 QQ 不必了，我已经很久没折腾了，提供不了有用的建议。
